---
storage:
  dbPath: "/var/mongodb/db/"
systemLog:
  path: "/data/log.mongod.log"
  destination: "file"
net:
  bindIp : "127.0.0.1,192.168.103.100"
  port: 27000
processManagement:
  fork : true
security:
    authorization: "enabled"